### ISSUE TITLE
Static linking on Alpine couldn't find LLVM static libraries

### ISSUE THREAD

**Issue by bnusunny** [KyleMayes/clang-sys#189]
Related to https://github.com/rust-lang/rust-bindgen/issues/2360#issuecomment-2367084230. 

[Here](https://github.com/llvm/llvm-project/blob/88bf774c565080e30e0a073676c316ab175303af/llvm/tools/llvm-config/llvm-config.cpp#L233) is the llvm-config code saying `--link-static` option is required for 'Link the component libraries statically'. 

clang-sys code [here](https://github.com/KyleMayes/clang-sys/blob/master/build/static.rs#L44) missed `--link-static` option.

**Comment by KyleMayes** [comment]
I released this as `v1.9.0`, but I realized there are some bad commits that broke users previously which led to me yanking the previous version (`v1.8.2`).

I will revisit this soon and remove those commits and release this in a new version.

**Comment by vadorovsky** [comment]
@KyleMayes I'm hitting the same issue and I see that 1.9.0 is still not released. Is there any chance we could get that change released?
